#!/bin/bash 


dirRE=$(find . -name 'RE*' -type d)
for dirR in $dirRE ; do
        cd $dirR
        read RE REnum<<<$(IFS="RE"; echo $dirR) 
        dirAlph=$(find . -name 'AoA*' -type d)
        for dirA in $dirAlph ; do
		cd $dirA
        	read AoA Anum<<<$(IFS="_"; echo $dirA)
                echo 'q.save' > finp
                addQvar < finp
                mv q.save q.save_old
                mv q.save_temp q.save
                cd ..
	done 
	cd ..
done






