#!/bin/bash 

varnames=( 'REV' 'RETC' 'FONSET1' 'FONSET2' 'FONSET3' 'FONSET' )
varlen=${#varnames[@]} 
varnum=( 0 3 4 5 6 7 8 )  # This array has an extra entry to start the sed at 0

dirRE=$(find . -name 'RE*' -type d)
for dirR in $dirRE ; do 
	cd $dirR
	dirAlph=$(find . -name 'AoA*' -type d)
	read RE NumR<<<$(IFS="E"; echo $dirR)
		for dirA in $dirAlph ; do	
			cd $dirA
			cp ../../Base/cgrid.3.inp .
		 	read AoA NumA<<<$(IFS="_"; echo $dirA)
                        sed "s/ALPHA = 0.0/ALPHA = $NumA/g" < cgrid.3.inp > temp
                        sed "s/REY = 0.0/REY = $NumR/g" < temp > temp2
                        mv temp2 cgrid.3.inp 
                        for (( i=0; i<${varlen}; i++ )) ; do
                	        sed "s/OUTVAR = ${varnum[i]}/OUTVAR = ${varnum[i+1]}/g" < cgrid.3.inp > temp
                                mv temp cgrid.3.inp
			        overrun cgrid.3 > output.out
			        echo ${varnames[i]} > finp 
                                echo '11' >> finp 
			        extractvar < finp
                        done		
			cd .. 	
                done 
	cd ..	
done






