#!/bin/bash 

echo "Enter the exponent in the boundary layer"
read lscale

echo "Enter the linear scale inside the boundary layer"
read lscale2

echo "Enter the name of the test"
read testname


rey=( 1.6 2.4 3.2 )
rLen=${#rey[@]} #Lenth of the Reynolds number array

alfa=(-5.0 -4.0 -3.0 -2.0 -1.0 0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 )
aLen=${#alfa[@]}



pattern="AoA"
for _dir in *"${pattern}"*; do
    [ -d "${_dir}" ] && dir="${_dir}" && break
done
echo "${dir}"or i in $(ls -d */); do echo ${i%%/}; done






