#!/bin/bash 

echo "Enter the exponent in the boundary layer"
read lscale

echo "Enter the linear scale inside the boundary layer"
read lscale2

echo "Enter the name of the test"
read testname

mkdir $testname
cd $testname 
cp ../go.x .
cp -r ../Base .

rey=( 1.6 2.4 3.2 )
rLen=${#rey[@]} #Lenth of the Reynolds number array

alfa=(-5.0 -4.0 -3.0 -2.0 -1.0 0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 )
aLen=${#alfa[@]}

rheight=0.0

for (( i=0; i<${rLen}; i++ )); do
	mkdir RE${rey[i]}
	cd RE${rey[i]}
        cp ../../run.naca64.slurm .
	for ((j=0; j<${aLen}; j++ )); do
       		mkdir AoA_${alfa[j]}
		cd AoA_${alfa[j]}
		cp ../../Base/n64.1.inp .
		cp ../../Base/mixsur.fmp .
		cp ../../Base/grid.ibi .
                cp ../../go.x .
		ln -s ../../Base/naca64grid.in  grid.in 
		sed "s/ALPHA = 0.0/ALPHA = ${alfa[j]}/g" < n64.1.inp > temp
		sed "s/REY = 0.0/REY = ${rey[i]}/g" < temp > temp2 
		sed "s/BCPAR1(1) = 0.0/BCPAR1(1) = $lscale2/g" < temp2 > temp3 
		sed "s/BCPAR2(1) = 0.0/BCPAR2(1) = $lscale/g" < temp3 > temp4
		sed "s/BCPAR1(2) = 0.0/BCPAR1(2) = $rheight/g" < temp4 > temp5
		rm -rf n64.1.inp temp temp2 temp3 temp4 
		mv temp5 naca.1.inp
	        cd ..
	done 
	cd ..
done






